import { Ubuntu, Roboto } from "next/font/google";
import "./globals.css";
import Nav from "./componentes/Nav";

const ubuntuSans = Ubuntu({
  variable: "--font-ubuntu-sans",
  subsets: ["latin"],
  weight: ['300', '400', '500', '700']
});

const robotoMono = Roboto({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuSans.variable} ${robotoMono.variable} antialiased`}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
